version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snap
    versions:
    - 1.0.3
  - dependency-name: bio
    versions:
    - 0.32.0
